### ISSUE TITLE
[Bug?] Overspend on repair & repair variables only updating after full repair paid for

### ISSUE THREAD

**Issue by ghsher** [lizverbeek/CRAB_model#3]
_If GitHub issues are not the best way to report these I'm so sorry & please let me know_

Right now it looks like, if a household can afford to spend some money on repair after a flood, but can't pay off the entire repair, their savings and consumption are affected and their spending on repair is tracked in a quasi-cumulative variable `self.repair_expenses`.

https://github.com/lizverbeek/CRAB_model/blob/bd7e4719778fa6bb2fa15c976fe4712ea51bf002/CRAB_agents.py#L229-L246

1. **Model effect problem:** if a household can ever afford to spend _more_ than their total incurred monetary damage, they will overspend
2.  **Model observation problem:** it is a bit difficult to track exactly how much a household spends on repair in a single timestep (it's possible, assuming the previous issue is fixed, by taking the difference between `self.repair_expenses[now]` & `self.repair_expenses[prev_time_step]`. It also makes the variables `self.monetary_damage`, `self.repair_expenses`, and `gov.total_repair_expenses` a bit misleadingly named, if you want to trace those as an output.

**Suggested fix**:

1. Update repair expenditure and remaining monetary damage at each timestep
2. Bound how much needs to be spent by how much was spent in previous timesteps (if doing 1., this is trivial)
3. Bound how much of consumption is used for repair by how much repair needs to be done (this is already done for savings, but not for consumption)
4. Bound how much of consumption is used for repair by how much has already been allocated from savings in this timestep

```python
def repair_damage(self) -> None:
    """Repair remaining flood damage and adjust consumption. """

    # Use savings to repair damage
    repair_capacity_savings = min(self.monetary_damage, self.net_worth)
    repair_spend_savings = min(self.monetary_damage, repair_capacity_savings)
    self.repair_expenses = repair_spend_savings
    self.monetary_damage -= repair_spend_savings
    self.net_worth -= repair_capacity_savings # Don't need max() based on defn of this var

    # Reduce consumption by reparation expenses
    repair_capacity_consumption = max(0, self.consumption - gov.unempl_subsidy)
    repair_spend_consumption = min(self.monetary_damage, repair_capacity_consumption)
    self.repair_expenses += repair_spend_consumption
    self.monetary_damage -= repair_spend_consumption
    self.consumption -= repair_spend_consumption # Again, this can't bring consumption lower than unemployment

    # Add repair expenses to regional total
    gov.total_repair_expenses += self.repair_expenses
```

This way, gov.total_repair_expenses reflects Construction demand as it happens. (Also FYI the bug fix to reset gov.total_repair_expenses to 0 hasn't been merged to the `multisector` branch)

**I'm not sure if the current implementation is intentional, like if households aren't supposed to be able to spend on repair until they can afford all of it. Either way I think the fact that households are forced to overspend on repair is relevant but maybe not that much.**

**Comment by lizverbeek** [comment]
> If GitHub issues are not the best way to report these I'm so sorry & please let me know

I think it is nice to also have these documented here, so no problem, this works well for me as well!

> I'm not sure if the current implementation is intentional, like if households aren't supposed to be able to spend on repair until they can afford all of it. Either way I think the fact that households are forced to overspend on repair is relevant but maybe not that much.

I am assigning the issue to @TabernaA, as it is more of a conceptual question and not a bug. Regarding the fact that household can only spend on repair until they can afford the full repairs costs: this **is intentional**. Regarding overspending: @TabernaA could you check this?

> This way, gov.total_repair_expenses reflects Construction demand as it happens. (Also FYI the bug fix to reset gov.total_repair_expenses to 0 hasn't been merged to the multisector branch)

Thanks for noticing, this bug fix only concerned the main branch. It seems this reset was already present in the `multisector` branch:
https://github.com/lizverbeek/CRAB_model/blob/ea8019076268d958f82bc6478c84436343646b5a/government.py#L305
so should work properly!

**Comment by ghsher** [comment]
> I think it is nice to also have these documented here, so no problem, this works well for me as well!

Great, I'll keep it up then 😅

> Regarding the fact that household can only spend on repair until they can afford the full repairs costs: this is intentional. Regarding overspending: @TabernaA could you check this?

Sorry, might have communicated it wrong. It makes sense that households only spend on repair until repairs are complete. What I meant is that their repairs don't "do anything" (i.e., don't update the actual consumption for the Construction industry, and don't decrease their damages) until the timestep in which they complete the repairs. It just knocks down their savings and consumption.
